---

collections:
  - name: community.docker
    version: 3.1.0
  - name: community.general
    version: 5.6.0
  - name: community.kubernetes
    version: 2.0.1
  - name: kubernetes.core
    version: 2.3.2
