all:
  children:
    kubernetes:
      children:
        primary_control_plane:
          hosts:
            control-plane-001:
              ansible_host: 10.69.1.1
        replica_control_plane:
          hosts:
            control-plane-002:
              ansible_host: 10.69.1.2
            control-plane-003:
              ansible_host: 10.69.1.3
        node_ubuntu_amd64:
          hosts:
            ubuntu-amd64-001:
              ansible_host: 10.69.2.1
            ubuntu-amd64-002:
              ansible_host: 10.69.2.2
            ubuntu-amd64-003:
              ansible_host: 10.69.2.3
            ubuntu-amd64-004:
              ansible_host: 10.69.2.4
            ubuntu-amd64-005:
              ansible_host: 10.69.2.5