all:
  children:
    kubernetes:
      children:
        primary_control_plane:
          hosts:
            control-plane-001:
              ansible_host: 10.69.1.1
        replica_control_plane:
          hosts:
            control-plane-002:
              ansible_host: 10.69.1.2
            control-plane-003:
              ansible_host: 10.69.1.3
        node_ubuntu_amd64:
          hosts:
            ubuntu-amd64-001:
              ansible_host: 10.69.2.1
            ubuntu-amd64-002:
              ansible_host: 10.69.2.2
            ubuntu-amd64-003:
              ansible_host: 10.69.2.3
            ubuntu-amd64-004:
              ansible_host: 10.69.2.4
            ubuntu-amd64-005:
              ansible_host: 10.69.2.5

# # If you are using proxmox, uncomment below for dynamic inventory support and comment the lines above

# plugin: community.general.proxmox
# url: https://changeme:8006
# user: root@pam
# password: 'changeme'
# validate_certs: false
# want_facts: true
# want_proxmox_nodes_ansible_host: false
# groups:
#   kubernetes: "'kubernetes' in ( proxmox_tags_parsed | list )"
#   primary_control_plane: "'primary_control_plane' in ( proxmox_tags_parsed | list )"
#   replica_control_plane: "'replica_control_plane' in ( proxmox_tags_parsed | list )"
#   node_ubuntu_amd64: "'node_ubuntu_amd64' in ( proxmox_tags_parsed | list )"
# compose:
#   ansible_host: proxmox_ipconfig0.ip | default( proxmox_net0.ip ) | ipaddr( 'address' )
