---

- name: Master - Setup
  hosts: primary_control_plane
  gather_facts: true
  roles:
    - role: master
      tags: master

- name: Replica/Node - Setup
  hosts: kubernetes
  gather_facts: true
  roles:
    - role: replica
      tags: replica

- name: Master - Restart gpu operator
  hosts: primary_control_plane
  gather_facts: false
  roles:
    - role: gpu
      tags: gpu
