---

- name: kubernetes - restart - gpu operator toolkit daemonset pods
  kubernetes.core.k8s:
    api_version: v1
    kind: Pod
    namespace: core
    label_selectors:
      - 'app=nvidia-container-toolkit-daemonset'
    state: absent
