---

- name: kubernetes - control-plane - set gpu labels to nvidia nodes
  kubernetes.core.k8s:
    definition:
      api_version: v1
      kind: Node
      metadata:
        name: '{{ ansible_hostname }}'
      labels:
        'nvidia.com/device-plugin.config=quadro-p2000'
    state: present
  when: nvidia_gpu_check.rc == 0
  delegate_to: "{{ item }}"
  with_items: '{{ groups.primary_control_plane }}'

- name: kubernetes - restart - gpu operator toolkit daemonset pods
  kubernetes.core.k8s:
    api_version: v1
    kind: Pod
    namespace: core
    label_selectors:
      - 'app=nvidia-container-toolkit-daemonset'
    state: absent
  when: inventory_hostname in groups['primary_control_plane']
