---

- name: os - install pip package
  ansible.builtin.apt:
    name: python3-pip
  become: true

- name: os - install kubernetes python dependency
  ansible.builtin.pip:
    name: kubernetes
  become: true
